#--------------------------------------------------------------------
#Executable generation area
#--------------------------------------------------------------------
clean   \
debug   \
prod	:

sauve	:	
	   @ echo	"Saving CONF component in RCS"
	   ../support/sauver $(SRC)
#--------------------------------------------------------------------
#Equivalences
#--------------------------------------------------------------------
SRC=	\
	bckdlist.exp \
	standard.sch \
	backd.conf \
	tapelist tapedev \
	Makefile \
